CREATE TABLE users
(
   USER_NO    INTEGER NOT NULL AUTO_INCREMENT COMMENT '사용자 번호',
   USER_ID    VARCHAR(20) NOT NULL COMMENT '아이디',
   USER_PASSWORD    VARCHAR(60) NOT NULL COMMENT '비밀번호',
   USER_NAME    VARCHAR(10) NOT NULL COMMENT '이름',
   INSERT_USER_NO    INTEGER NOT NULL COMMENT '등록자',
   INSERT_DATE    DATETIME NOT NULL COMMENT '등록일자',
   MODIFY_USER_NO    INTEGER NOT NULL  COMMENT '수정자',
   MODIFY_DATE    DATETIME NOT NULL COMMENT '수정일자',
   PRIMARY KEY(USER_NO),
   UNIQUE KEY UK_USER_ID (USER_ID),
   CONSTRAINT FK_USER_INSERT_USER FOREIGN KEY (INSERT_USER_NO) REFERENCES users (USER_NO),
   CONSTRAINT FK_USER_MODIFY_USER FOREIGN KEY (MODIFY_USER_NO) REFERENCES users (USER_NO)
) COMMENT '사용자';

CREATE TABLE post
(
   POST_NO    INTEGER NOT NULL AUTO_INCREMENT COMMENT '게시판 번호',
   TITLE    VARCHAR(100) NOT NULL COMMENT '제목',
   CONTENT    LONGTEXT NOT NULL COMMENT '내용',
   VIEW_COUNT    INTEGER NOT NULL COMMENT '조회수',
   DELETE_YN    CHAR NOT NULL COMMENT '삭제여부',
   INSERT_USER_NO    INTEGER NOT NULL COMMENT '등록자',
   INSERT_DATE    DATETIME NOT NULL COMMENT '등록일자',
   MODIFY_USER_NO    INTEGER COMMENT '수정자',
   MODIFY_DATE    DATETIME COMMENT '수정일자',
   PRIMARY KEY(POST_NO),
   CONSTRAINT FK_POST_INSERT_USER FOREIGN KEY (INSERT_USER_NO) REFERENCES users (USER_NO),
   CONSTRAINT FK_POST_MODIFY_USER FOREIGN KEY (MODIFY_USER_NO) REFERENCES users (USER_NO)
) COMMENT '게시판';

INSERT INTO users (USER_NO, USER_ID, USER_PASSWORD, USER_NAME, INSERT_USER_NO, INSERT_DATE, MODIFY_USER_NO, MODIFY_DATE) VALUES ('1', 'ADMIN', '$10$IXgHDWTH/FTdOg0pu4jSLuobXB70i1VSaQEl4ZDBTjrUXRA5UW9PK', '관리자', 1, NOW(), 1, NOW());
