# Server
server:
  port: 8000
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/mindshare?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:rhakqjsro12!}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
